--liquibase formatted sql

--changeset GonzaloBaldassi:Insercion_Clases_Licencias
INSERT INTO license_class (name, description) VALUES
('B1', 'AUTOMOVILES, UTILITARIOS, CAMIONETAS Y CASAS RODANTES HASTA 3.500 KG DE PESO TOTAL.'),
('B2', 'AUTOMOVILES, UTILITARIOS, CAMIONETAS Y CASAS RODANTES HASTA 3.500 KG DE PESO TOTAL. ACOPLADO O SEMIRREMOLQUE HASTA 750 KG.'),
('D1', 'AUTOMOTORES PARA SERVICIOS DE TRANSPORTE DE PASAJEROS HASTA OCHO (8) PLAZAS, EXCLUIDO EL CONDUCTOR.'),
('D2', 'AUTOMOTORES PARA SERVICIOS DE TRANSPORTE DE PASAJEROS DE MAS DE OCHO (8) PLAZAS Y HASTA VEINTE (20) PLAZAS, EXCLUIDO EL CONDUCTOR.'),
('D3', 'AUTOMOTORES PARA SERVICIOS DE TRANSPORTE DE PASAJEROS DE MAS DE VEINTE (20) PLAZAS, EXCLUIDO EL CONDUCTOR.');