--liquibase formatted sql
--changeset SantiGodoy:crear_rol_conductor_por_defecto_01 runOnChange:true splitStatements:false
INSERT INTO public."role" (id, "name") VALUES(2, 'ROLE_DRIVER')
 ON CONFLICT (id) DO NOTHING;

-- changeset SantiGodoy:create_province_table_01 
CREATE TABLE IF NOT EXISTS public.province (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255)
);
COMMENT ON TABLE public.province IS 'Almacena las provincias.';
COMMENT ON COLUMN public.province.name IS 'Nombre único de la provincia.';

-- changeset SantiGodoy:create_city_table_01 
CREATE TABLE IF NOT EXISTS public.city (
    id BIGSERIAL PRIMARY KEY,
    zip_code VARCHAR(50) NOT NULL, 
    name VARCHAR(100) NOT NULL,
    province_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),

    CONSTRAINT fk_city_province FOREIGN KEY (province_id) REFERENCES public.province(id),
    CONSTRAINT uq_city_name_province UNIQUE (name, province_id)
);
COMMENT ON TABLE public.city IS 'Almacena las ciudades y su provincia asociada.';
COMMENT ON COLUMN public.city.name IS 'Nombre de la ciudad.';
COMMENT ON COLUMN public.city.province_id IS 'ID de la provincia a la que pertenece la ciudad.';


--changeset SantiGodoy:insert_argentinian_provinces_01 
-- Este changeset inserta las 23 provincias de Argentina y CABA.
-- created_at se setea con la fecha actual, ya que el @PrePersist de JPA solo actúa al insertar desde la app.
INSERT INTO public."province" (id, "name", "created_at") VALUES (1, 'BUENOS AIRES', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (2, 'CATAMARCA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (3, 'CHACO', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (4, 'CHUBUT', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (5, 'CORDOBA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (6, 'CORRIENTES', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (7, 'ENTRE RIOS', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (8, 'FORMOSA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (9, 'JUJUY', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (10, 'LA PAMPA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (11, 'LA RIOJA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (12, 'MENDOZA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (13, 'MISIONES', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (14, 'NEUQUEN', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (15, 'RIO NEGRO', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (16, 'SALTA', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (17, 'SAN JUAN', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (18, 'SAN LUIS', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (19, 'SANTA CRUZ', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (20, 'SANTA FE', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (21, 'SANTIAGO DEL ESTERO', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (22, 'TIERRA DEL FUEGO', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (23, 'TUCUMAN', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."province" (id, "name", "created_at") VALUES (24, 'CIUDAD AUTONOMA DE BUENOS AIRES', NOW()) ON CONFLICT (id) DO NOTHING;


--changeset SantiGodoy:drop_unique_constraint_on_zip_code_02
ALTER TABLE public.city
DROP CONSTRAINT ukfywt1lwmd5r4o5m3gqkt1i1bd;

--changeset SantiGodoy:insert_initial_cities_01
-- Este changeset inserta las localidades de la provincia de Córdoba.
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (1, '2651', 'ALDEA SANTA MARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (2, '5281', 'ALTO DE LOS QUEBRACHOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (3, '5199', 'AMBOY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (4, '5299', 'AMBUL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (5, '5905', 'ANA ZUMARAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (6, '5889', 'ARROYO DE LOS PATOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (7, '2671', 'ASSUNTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (8, '5225', 'ATAHONA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (9, '5212', 'AVELLANEDA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (10, '5285', 'BANADO DE SOTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (11, '5155', 'CABALANGO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (12, '5244', 'CAMINIAGA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (13, '5221', 'CANDELARIA SUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (14, '5231', 'CAPILLA DE SITON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (15, '5101', 'CAPILLA DE LOS REMEDIOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (16, '5162', 'CASA GRANDE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (17, '5961', 'CANADA DE MACHADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (18, '5221', 'CANADA DE RIO PINTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (19, '5817', 'CANADA DEL SAUCE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (20, '5244', 'CERRO COLORADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (21, '5229', 'CHALACEA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (22, '5871', 'CHANCANI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (23, '5282', 'CHARBONIER', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (24, '5248', 'CHANAR VIEJO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (25, '5805', 'CHUCUL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (26, '5246', 'CHURQUI CANADA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (27, '5218', 'CHUNA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (28, '5218', 'CHUNA HUASI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (29, '5289', 'CIENAGA DEL CORO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (30, '2413', 'COLONIA ANITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (31, '2659', 'COLONIA BARGE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (32, '2651', 'COLONIA BREMEN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (33, '2413', 'COLONIA ITURRASPE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (34, '5135', 'COLONIA LAS CUATRO ESQUINAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (35, '2433', 'COLONIA LAS PICHANAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (36, '2421', 'COLONIA SAN PEDRO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (37, '2413', 'COLONIA VALTELINA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (38, '5221', 'COLONIA VICENTE AGUERO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (39, '5865', 'COLONIA VIDELA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (40, '5129', 'COMECHINGONES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (41, '5873', 'CONLARA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (42, '5201', 'COPACABANA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (43, '5287', 'CRUZ DE CANA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (44, '5153', 'CUESTA BLANCA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (45, '5135', 'DIEGO DE ROJAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (46, '5189', 'DIQUE CHICO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (47, '5272', 'EL CHACHO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (48, '5129', 'EL CRISPIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (49, '5107', 'EL MANZANO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (50, '6121', 'EL RASTREADOR', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (51, '5249', 'EL RODEO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (52, '5131', 'ESQUINA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (53, '5152', 'ESTANCIA VIEJA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (54, '5291', 'ESTANCIA DE GUADALUPE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (55, '5248', 'EUFRASIO LOZA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (56, '5187', 'FALDA DEL CARMEN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (57, '5933', 'GENERAL FOTHERINGHAM', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (58, '5281', 'GUANACO MUERTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (59, '5285', 'GUASAPAMPA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (60, '5249', 'GUTEMBERG', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (61, '5987', 'IMPIRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (62, '5125', 'KILOMETRO 658', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (63, '5270', 'LA BATEA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (64, '5801', 'LA CAROLINA EL POTOSI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (65, '5194', 'LA CUMBRECITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (66, '5285', 'LA HIGUERA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (67, '5186', 'LA PAISANITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (68, '5117', 'LA PAMPA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (69, '5285', 'LA PLAYA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (70, '5875', 'LA POBLACION', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (71, '5227', 'LA POSTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (72, '5135', 'LA QUINTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (73, '589', 'LA RANCHERITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (74, '5233', 'LA RINCONADA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (75, '5189', 'LA SERRANITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (76, '5801', 'LAS ALBAHACAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (77, '5851', 'LAS BAJADAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (78, '5819', 'LAS CALERAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (79, '5885', 'LAS CALLES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (80, '5870', 'LAS CANADAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (81, '5135', 'LAS GRAMILLAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (82, '5931', 'LAS ISLETILLAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (83, '5201', 'LAS PALMAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (84, '5819', 'LAS PENAS SUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (85, '5285', 'LAS PLAYAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (86, '5885', 'LAS RABONAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (87, '5137', 'LAS SALADAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (88, '6128', 'LEGUIZAMON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (89, '5101', 'LOS CEDROS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (90, '5227', 'LOS CHANARITOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (91, '5216', 'AGUA HEDIONDA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (92, '5885', 'LOS HORNILLOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (93, '5249', 'LOS HOYOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (94, '5281', 'LOS MISTOLES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (95, '5189', 'LOS MOLINOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (96, '5225', 'LOS POZOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (97, '5194', 'LOS REARTES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (98, '5299', 'LOS TALARES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (99, '5859', 'LUTTI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (100, '5875', 'LUYABA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (101, '5839', 'MALENA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (102, '5227', 'MAQUINISTA GALLINI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (103, '5831', 'MAYU SUMAJ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (104, '5281', 'MEDIA NARANJA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (105, '6271', 'NICOLAS BRUZZONE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (106, '5280', 'OLIVARES DE SAN NICOLAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (107, '6227', 'ONAGOITY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (108, '6121', 'PACHECO DE MELO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (109, '5931', 'PAMPAYASTA NORTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (110, '5893', 'PANAHOLMA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (111, '5191', 'PARQUE CALMAYO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (112, '5284', 'PASO VIEJO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (113, '5803', 'PASO DEL DURAZNO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (114, '6271', 'PINCEN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (115, '2411', 'PLAZA LUXARDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (116, '5137', 'PLAZA DE MERCEDES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (117, '5189', 'POTRERO DE GARAY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (118, '5209', 'POZO NUEVO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (119, '5233', 'PUESTO DE CASTRO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (120, '5839', 'PUNTA DEL AGUA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (121, '5119', 'RAFAEL GARCIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (122, '6271', 'RANQUELES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (123, '5246', 'RAYO CORTADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (124, '5961', 'RINCON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (125, '5233', 'ROSARIO DEL SALADILLO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (126, '6134', 'RIO BAMBA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (127, '5875', 'SAGRADA FAMILIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (128, '2587', 'SALADILLO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (129, '5187', 'SAN CLEMENTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (130, '5297', 'SAN GERONIMO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (131, '5199', 'SAN IGNACIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (132, '6123', 'SAN JOAQUIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (133, '5893', 'SAN LORENZO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (134, '5199', 'SAN ROQUE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (135, '5871', 'SAN VICENTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (136, '5246', 'SANTA ELENA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (137, '5182', 'SAUCE ARRIBA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (138, '5857', 'SEGUNDA USINA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (139, '5281', 'SIMBOLAR', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (140, '5837', 'SUCO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (141, '5297', 'TALA CANADA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (142, '5153', 'TALA HUASI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (143, '5291', 'TALAINI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (144, '5131', 'TINOCO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (145, '5139', 'TORO PUJIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (146, '5289', 'TOSNO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (147, '5284', 'TUCLAME', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (148, '5189', 'VALLE DE ANISACATE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (149, '5199', 'VILLA AMANCAY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (150, '5249', 'VILLA CANDELARIA NORTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (151, '5107', 'VILLA CERRO AZUL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (152, '5189', 'VILLA CIUDAD PARQUE LOS REARTES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (153, '5887', 'VILLA CIUDAD DE AMERICA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (154, '5801', 'VILLA EL CHACAY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (155, '2594', 'VILLA ELISA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (156, '5212', 'VILLA GUTIERREZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (157, '5189', 'VILLA LA BOLSA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (158, '5186', 'VILLA LOS AROMOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (159, '2551', 'VILLA LOS PATOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (160, '5152', 'VILLA PARQUE SIQUIMAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (161, '5859', 'VILLA QUILLINZO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (162, '5947', 'VILLA SAN ESTEBAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (163, '5189', 'VILLA SAN ISIDRO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (164, '5871', 'VILLA SARMIENTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (165, '5299', 'VILLA DE POCHO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (166, '5186', 'VILLA DEL PRADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (167, '6144', 'WASHINGTON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (168, '5833', 'ACHIRAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (169, '5843', 'ADELIA MARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (170, '5107', 'AGUA DE ORO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (171, '5813', 'ALCIRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (172, '2686', 'ALEJANDRO ROCA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (173, '2662', 'ALEJO LEDESMA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (174, '5949', 'ALICIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (175, '5854', 'ALMAFUERTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (176, '5801', 'ALPA CORRAL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (177, '5186', 'ALTA GRACIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (178, '5907', 'ALTO ALEGRE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (179, '2417', 'ALTOS DE CHIPION', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (180, '5189', 'ANISACATE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (181, '2624', 'ARIAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (182, '2434', 'ARROYITO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (183, '5909', 'ARROYO ALGODON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (184, '5917', 'ARROYO CABRAL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (185, '5901', 'AUSONIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (186, '2572', 'BALLESTEROS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (187, '2572', 'BALLESTEROS SUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (188, '5141', 'BALNEARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (189, '2550', 'BELL VILLE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (190, '5807', 'BENGOLEA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (191, '2664', 'BENJAMIN GOULD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (192, '5817', 'BERROTARAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (193, '5158', 'BIALET MASSE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (194, '5119', 'BOUWER', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (195, '2419', 'BRINKMANN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (196, '6225', 'BUCHARDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (197, '5845', 'BULNES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (198, '5969', 'CALCHIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (199, '5965', 'CALCHIN OESTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (200, '2585', 'CAMILO ALDAO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (201, '2650', 'CANALS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (202, '5963', 'CAPILLA DEL CARMEN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (203, '5184', 'CAPILLA DEL MONTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (204, '2645', 'CAPITAN GENERAL BERNARDO O', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (205, '5805', 'CARNERILLO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (206, '5915', 'CARRILOBO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (207, '2625', 'CAVANAGH', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (208, '5229', 'CANADA DE LUQUE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (209, '5837', 'CHAJAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (210, '5807', 'CHARRAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (211, '2675', 'CHAZON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (212, '2561', 'CHILIBROSTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (213, '2559', 'CINTRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (214, '5965', 'COLAZO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (215, '5987', 'COLONIA ALMADA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (216, '2651', 'COLONIA BISMARCK', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (217, '5223', 'COLONIA CAROYA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (218, '2645', 'COLONIA ITALIANA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (219, '2424', 'COLONIA MARINA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (220, '2423', 'COLONIA PROSPERIDAD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (221, '2426', 'COLONIA SAN BARTOLOME', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (222, '5101', 'COLONIA TIROLESA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (223, '2419', 'COLONIA VIGNAUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (224, '5811', 'CORONEL BAIGORRIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (225, '5847', 'CORONEL MOLDES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (226, '2645', 'CORRAL DE BUSTOS IFFLINGER', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (227, '5853', 'CORRALITO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (228, '5166', 'COSQUIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (229, '5961', 'COSTA SACATE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (230, '2189', 'CRUZ ALTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (231, '5280', 'CRUZ DEL EJE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (232, '5000', 'CORDOBA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (233, '5919', 'DALMACIO VELEZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (234, '6271', 'DEL CAMPILLO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (235, '5121', 'DESPENADEROS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (236, '2424', 'DEVOTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (237, '5200', 'DEAN FUNES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (238, '5947', 'EL ARANADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (239, '5281', 'EL BRETE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (240, '5951', 'EL FORTIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (241, '2432', 'EL TIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (242, '5815', 'ELENA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (243, '5856', 'EMBALSE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (244, '5145', 'ESTACION GENERAL PAZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (245, '5045', 'ESTACION JUAREZ CELMAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (246, '2681', 'ETRURIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (247, '2413', 'FREYRE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (248, '2583', 'GENERAL BALDISSERA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (249, '5809', 'GENERAL CABRERA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (250, '5923', 'GENERAL DEHEZA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (251, '6132', 'GENERAL LEVALLE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (252, '2592', 'GENERAL ROCA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (253, '2627', 'GUATIMOZIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (254, '5929', 'HERNANDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (255, '6121', 'HUANCHILLA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (256, '5174', 'HUERTA GRANDE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (257, '6270', 'HUINCA RENANCO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (258, '2557', 'IDIAZABAL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (259, '2587', 'INRIVILLE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (260, '2661', 'ISLA VERDE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (261, '6271', 'ITALO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (262, '5984', 'JAMES CRAIK', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (263, '5220', 'JESUS MARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (264, '6127', 'JOVITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (265, '2553', 'JUSTINIANO POSSE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (266, '5151', 'LA CALERA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (267, '2670', 'LA CARLOTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (268, '6142', 'LA CAUTIVA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (269, '6101', 'LA CESIRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (270, '5859', 'LA CRUZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (271, '5178', 'LA CUMBRE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (272, '5172', 'LA FALDA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (273, '2426', 'LA FRANCIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (274, '5115', 'LA GRANJA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (275, '5284', 'LA LAGUNA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (276, '5925', 'LA PALESTINA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (277, '2417', 'LA PAQUITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (278, '5137', 'LA PARA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (279, '5879', 'LA PAZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (280, '5911', 'LA PLAYOSA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (281, '5101', 'LA PUERTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (282, '2435', 'LA TORDILLA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (283, '2657', 'LABORDE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (284, '6120', 'LABOULAYE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (285, '5974', 'LAGUNA LARGA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (286, '5848', 'LAS ACEQUIAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (287, '5231', 'LAS ARRIAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (288, '5805', 'LAS HIGUERAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (289, '5965', 'LAS JUNTURAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (290, '5921', 'LAS PERDICES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (291, '5238', 'LAS PENAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (292, '5885', 'LAS TAPIAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (293, '5941', 'LAS VARAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (294, '5940', 'LAS VARILLAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (295, '5839', 'LAS VERTIENTES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (296, '2594', 'LEONES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (297, '5871', 'LOS CERRILLOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (298, '2684', 'LOS CISNES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (299, '5182', 'LOS COCOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (300, '5823', 'LOS CONDORES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (301, '2581', 'LOS SURGENTES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (302, '5901', 'LOS ZORROS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (303, '5101', 'LOZADA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (304, '5917', 'LUCA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (305, '5216', 'LUCIO VICTORIO MANSILLA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (306, '5967', 'LUQUE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (307, '5101', 'MALAGUENO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (308, '5125', 'MALVINAS ARGENTINAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (309, '5988', 'MANFREDI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (310, '2580', 'MARCOS JUAREZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (311, '5139', 'MARULL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (312, '5965', 'MATORRALES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (313, '6271', 'MATTALDI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (314, '6123', 'MELO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (315, '5107', 'MENDIOLAZA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (316, '5125', 'MI GRANJA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (317, '5889', 'MINA CLAVERO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (318, '5143', 'MIRAMAR DE ANSENUZA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (319, '2589', 'MONTE BUEY', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (320, '2564', 'MONTE LENA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (321, '2659', 'MONTE MAIZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (322, '5119', 'MONTE RALO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (323, '5831', 'MONTE DE LOS GAUCHOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (324, '5125', 'MONTECRISTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (325, '2568', 'MORRISON', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (326, '2421', 'MORTEROS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (327, '2563', 'NOETINGER', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (328, '5887', 'NONO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (329, '5225', 'OBISPO TREJO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (330, '5807', 'OLAETA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (331, '5980', 'OLIVA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (332, '5986', 'ONCATIVO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (333, '2555', 'ORDONEZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (334, '5931', 'PAMPAYASTA SUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (335, '2679', 'PASCANAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (336, '5925', 'PASCO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (337, '5972', 'PILAR', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (338, '5125', 'PIQUILLIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (339, '2415', 'PORTENA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (340, '5913', 'POZO DEL MOLLE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (341, '2651', 'PUEBLO ITALIANO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (342, '2423', 'QUEBRACHO HERRADO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (343, '5214', 'QUILINO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (344, '5803', 'REDUCCION', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (345, '6128', 'ROSALES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (346, '5111', 'RIO CEBALLOS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (347, '5800', 'RIO CUARTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (348, '5127', 'RIO PRIMERO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (349, '5960', 'RIO SEGUNDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (350, '5850', 'RIO TERCERO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (351, '5821', 'RIO DE LOS SAUCES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (352, '5945', 'SACANTA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (353, '2525', 'SAIRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (354, '5149', 'SALDAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (355, '5295', 'SALSACATE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (356, '5113', 'SALSIPUEDES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (357, '5829', 'SAMPACHO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (358, '5191', 'SAN AGUSTIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (359, '5153', 'SAN ANTONIO DE ARREDONDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (360, '2559', 'SAN ANTONIO DE LITIN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (361, '5841', 'SAN BASILIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (362, '5291', 'SAN CARLOS MINAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (363, '5182', 'SAN ESTEBAN', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (364, '2400', 'SAN FRANCISCO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (365, '5209', 'SAN FRANCISCO DEL CHANAR', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (366, '5875', 'SAN JAVIER Y YACANTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (367, '5871', 'SAN JOSE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (368, '5244', 'SAN JOSE DE LA DORMIDA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (369, '5216', 'SAN JOSE DE LAS SALINAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (370, '5282', 'SAN MARCOS SIERRA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (371, '2566', 'SAN MARCOS SUD', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (372, '5871', 'SAN PEDRO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (373, '5205', 'SAN PEDRO NORTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (374, '5825', 'SANTA CATALINA HOLMBERG', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (375, '2671', 'SANTA EUFEMIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (376, '5164', 'SANTA MARIA DE PUNILLA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (377, '5196', 'SANTA ROSA DE CALAMUCHITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (378, '5125', 'SANTIAGO TEMPLE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (379, '5212', 'SARMIENTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (380, '5943', 'SATURNINO MARIA LASPIUR', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (381, '5231', 'SEBASTIAN ELCANO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (382, '2419', 'SEEBER', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (383, '6125', 'SERRANO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (384, '5270', 'SERREZUELA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (385, '5907', 'SILVIO PELLICO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (386, '5220', 'SINSACATE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (387, '5933', 'TANCACHA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (388, '5155', 'TANTI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (389, '5927', 'TICINO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (390, '5123', 'TOLEDO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (391, '6141', 'TOSQUITA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (392, '2436', 'TRANSITO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (393, '5936', 'TIO PUJIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (394, '2677', 'UCACHA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (395, '5109', 'UNQUILLO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (396, '5168', 'VALLE HERMOSO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (397, '2671', 'VIAMONTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (398, '6140', 'VICUNA MACKENNA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (399, '5105', 'VILLA ALLENDE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (400, '5935', 'VILLA ASCASUBI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (401, '5152', 'VILLA CARLOS PAZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (402, '2433', 'VILLA CONCEPCION DEL TIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (403, '5891', 'VILLA CURA BROCHERO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (404, '5870', 'VILLA DOLORES', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (405, '5137', 'VILLA FONTANA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (406, '5194', 'VILLA GENERAL BELGRANO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (407, '5176', 'VILLA GIARDINO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (408, '6275', 'VILLA HUIDOBRO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (409, '5220', 'VILLA MARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (410, '5903', 'VILLA NUEVA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (411, '5101', 'VILLA PARQUE SANTA ANA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (412, '6128', 'VILLA ROSSI', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (413, '5864', 'VILLA RUMIPAL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (414, '5153', 'VILLA RIO ICHO CRUZ', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (415, '5152', 'VILLA SANTA CRUZ DEL LAGO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (416, '5133', 'VILLA SANTA ROSA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (417, '5871', 'VILLA SARMIENTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (418, '5203', 'VILLA TULUMBA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (419, '6273', 'VILLA VALERIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (420, '5197', 'VILLA YACANTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (421, '5248', 'VILLA DE MARIA', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (422, '5284', 'VILLA DE SOTO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (423, '5885', 'VILLA DE LAS ROSAS', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (424, '5862', 'VILLA DEL DIQUE', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (425, '5963', 'VILLA DEL ROSARIO', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (426, '5236', 'VILLA DEL TOTORAL', 5, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."city" (id,"zip_code","name",province_id,"created_at") VALUES (427, '2655', 'WENCESLAO ESCALANTE', 5, NOW()) ON CONFLICT (id) DO NOTHING;