--liquibase formatted sql

--changeset AgustinAnil:crear_tabla_media
CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    bucket VARCHAR(50) NOT NULL,
    category VARCHAR(50) not null,
    object_key TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (bucket, object_key),
    CONSTRAINT fk_user_id FOREIGN key (user_id) REFERENCES "users"(id) ON DELETE CASCADE
);

COMMENT ON COLUMN public.media.user_id IS 'A quien corresponde la imagen';
COMMENT ON COLUMN public.media.bucket IS 'Bucket de Cloudflare';
COMMENT ON COLUMN public.media.category IS 'Categoria de la imagen, PROFILE para el perfil, VEHICLE para vehiculos, etc';
COMMENT ON COLUMN public.media.object_key IS 'Identificador de la imagen en el bucket';
COMMENT ON COLUMN public.media.filename IS 'Nombre del archivo';
COMMENT ON COLUMN public.media.content_type IS 'Tipo de contenido de la imagen';
COMMENT ON COLUMN public.media.byte_size IS 'Tamanio de la imagen';
COMMENT ON COLUMN public.media.created_at IS 'Fecha de cracion';

CREATE UNIQUE INDEX uq_media_profile_primary
  ON media(user_id)
  WHERE category = 'PROFILE';