--liquibase formatted sql

--changeset SantiagoGodoy:crear_localidades_y_provincias
INSERT INTO public."province" (id, "name") VALUES (1, 'BUENOS AIRES');
INSERT INTO public."province" (id, "name") VALUES (2, 'CATAMARCA');
INSERT INTO public."province" (id, "name") VALUES (3, 'CHACO');
INSERT INTO public."province" (id, "name") VALUES (4, 'CHUBUT');
INSERT INTO public."province" (id, "name") VALUES (5, 'CORDOBA');
INSERT INTO public."province" (id, "name") VALUES (6, 'CORRIENTES');
INSERT INTO public."province" (id, "name") VALUES (7, 'ENTRE RIOS');
INSERT INTO public."province" (id, "name") VALUES (8, 'FORMOSA');
INSERT INTO public."province" (id, "name") VALUES (9, 'JUJUY');
INSERT INTO public."province" (id, "name") VALUES (10, 'LA PAMPA');
INSERT INTO public."province" (id, "name") VALUES (11, 'LA RIOJA');
INSERT INTO public."province" (id, "name") VALUES (12, 'MENDOZA');
INSERT INTO public."province" (id, "name") VALUES (13, 'MISIONES');
INSERT INTO public."province" (id, "name") VALUES (14, 'NEUQUEN');
INSERT INTO public."province" (id, "name") VALUES (15, 'RIO NEGRO');
INSERT INTO public."province" (id, "name") VALUES (16, 'SALTA');
INSERT INTO public."province" (id, "name") VALUES (17, 'SAN JUAN');
INSERT INTO public."province" (id, "name") VALUES (18, 'SAN LUIS');
INSERT INTO public."province" (id, "name") VALUES (19, 'SANTA CRUZ');
INSERT INTO public."province" (id, "name") VALUES (20, 'SANTA FE');
INSERT INTO public."province" (id, "name") VALUES (21, 'SANTIAGO DEL ESTERO');
INSERT INTO public."province" (id, "name") VALUES (22, 'TIERRA DEL FUEGO');
INSERT INTO public."province" (id, "name") VALUES (23, 'TUCUMAN');
INSERT INTO public."province" (id, "name") VALUES (24, 'CIUDAD AUTONOMA DE BUENOS AIRES');


INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (1, '2651', 'COLONIA SANTA MARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (2, '5281', 'ALTO DE LOS QUEBRACHOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (3, '5199', 'AMBOY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (4, '5299', 'AMBUL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (5, '5905', 'ANA ZUMARAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (6, '5889', 'ARROYO DE LOS PATOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (7, '2671', 'ASSUNTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (8, '5225', 'ATAHONA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (9, '5212', 'AVELLANEDA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (10, '5285', 'BANADO DE SOTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (11, '5155', 'CABALANGO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (12, '5244', 'CAMINIAGA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (13, '5221', 'CANDELARIA SUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (14, '5231', 'CAPILLA DE SITON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (15, '5101', 'CAPILLA DE LOS REMEDIOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (16, '5162', 'CASA GRANDE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (17, '5961', 'CANADA DE MACHADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (18, '5221', 'CANADA DE RIO PINTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (19, '5817', 'CANADA DEL SAUCE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (20, '5244', 'CERRO COLORADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (21, '5229', 'CHALACEA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (22, '5871', 'CHANCANI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (23, '5282', 'CHARBONIER', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (24, '5248', 'CHANAR VIEJO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (25, '5805', 'CHUCUL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (26, '5246', 'CHURQUI CANADA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (27, '5218', 'CHUNA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (28, '5218', 'CHUNA HUASI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (29, '5289', 'CIENAGA DEL CORO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (30, '2413', 'COLONIA ANITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (31, '2659', 'COLONIA BARGE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (32, '2651', 'COLONIA BREMEN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (33, '2413', 'COLONIA ITURRASPE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (34, '5135', 'COLONIA LAS CUATRO ESQUINAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (35, '2433', 'COLONIA LAS PICHANAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (36, '2421', 'COLONIA SAN PEDRO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (37, '2413', 'COLONIA VALTELINA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (38, '5221', 'COLONIA VICENTE AGUERO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (39, '5865', 'COLONIA VIDELA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (40, '5129', 'COMECHINGONES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (41, '5873', 'CONLARA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (42, '5201', 'COPACABANA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (43, '5287', 'CRUZ DE CANA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (44, '5153', 'CUESTA BLANCA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (45, '5135', 'DIEGO DE ROJAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (46, '5189', 'DIQUE CHICO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (47, '5272', 'EL CHACHO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (48, '5129', 'EL CRISPIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (49, '5107', 'EL MANZANO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (50, '6121', 'EL RASTREADOR', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (51, '5249', 'EL RODEO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (52, '5131', 'ESQUINA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (53, '5152', 'ESTANCIA VIEJA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (54, '5291', 'ESTANCIA DE GUADALUPE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (55, '5248', 'EUFRASIO LOZA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (56, '5187', 'FALDA DEL CARMEN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (57, '5933', 'GENERAL FOTHERINGHAM', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (58, '5281', 'GUANACO MUERTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (59, '5285', 'GUASAPAMPA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (60, '5249', 'GUTEMBERG', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (61, '5987', 'IMPIRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (62, '5125', 'KILOMETRO 658', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (63, '5270', 'LA BATEA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (64, '5801', 'LA CAROLINA EL POTOSI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (65, '5194', 'LA CUMBRECITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (66, '5285', 'LA HIGUERA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (67, '5186', 'LA PAISANITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (68, '5117', 'LA PAMPA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (69, '5285', 'LA PLAYA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (70, '5875', 'LA POBLACION', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (71, '5227', 'LA POSTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (72, '5135', 'LA QUINTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (73, '589', 'LA RANCHERITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (74, '5233', 'LA RINCONADA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (75, '5189', 'LA SERRANITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (76, '5801', 'LAS ALBAHACAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (77, '5851', 'LAS BAJADAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (78, '5819', 'LAS CALERAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (79, '5885', 'LAS CALLES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (80, '5870', 'LAS CANADAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (81, '5135', 'LAS GRAMILLAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (82, '5931', 'LAS ISLETILLAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (83, '5201', 'LAS PALMAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (84, '5819', 'LAS PENAS SUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (85, '5285', 'LAS PLAYAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (86, '5885', 'LAS RABONAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (87, '5137', 'LAS SALADAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (88, '6128', 'LEGUIZAMON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (89, '5101', 'LOS CEDROS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (90, '5227', 'LOS CHANARITOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (91, '5216', 'AGUA HEDIONDA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (92, '5885', 'LOS HORNILLOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (93, '5249', 'LOS HOYOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (94, '5281', 'LOS MISTOLES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (95, '5189', 'LOS MOLINOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (96, '5225', 'LOS POZOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (97, '5194', 'LOS REARTES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (98, '5299', 'LOS TALARES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (99, '5859', 'LUTTI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (100, '5875', 'LUYABA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (101, '5839', 'MALENA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (102, '5227', 'MAQUINISTA GALLINI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (103, '5831', 'MAYU SUMAJ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (104, '5281', 'MEDIA NARANJA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (105, '6271', 'NICOLAS BRUZZONE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (106, '5280', 'OLIVARES DE SAN NICOLAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (107, '6227', 'ONAGOITY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (108, '6121', 'PACHECO DE MELO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (109, '5931', 'PAMPAYASTA NORTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (110, '5893', 'PANAHOLMA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (111, '5191', 'PARQUE CALMAYO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (112, '5284', 'PASO VIEJO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (113, '5803', 'PASO DEL DURAZNO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (114, '6271', 'PINCEN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (115, '2411', 'PLAZA LUXARDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (116, '5137', 'PLAZA DE MERCEDES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (117, '5189', 'POTRERO DE GARAY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (118, '5209', 'POZO NUEVO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (119, '5233', 'PUESTO DE CASTRO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (120, '5839', 'PUNTA DEL AGUA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (121, '5119', 'RAFAEL GARCIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (122, '6271', 'RANQUELES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (123, '5246', 'RAYO CORTADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (124, '5961', 'RINCON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (125, '5233', 'VILLA ROSARIO DEL SALADILLO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (126, '6134', 'RIO BAMBA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (127, '5875', 'SAGRADA FAMILIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (128, '2587', 'SALADILLO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (129, '5187', 'SAN CLEMENTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (130, '5297', 'SAN GERONIMO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (131, '5199', 'SAN IGNACIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (132, '6123', 'SAN JOAQUIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (133, '5893', 'SAN LORENZO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (134, '5199', 'SAN ROQUE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (135, '5871', 'SAN VICENTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (136, '5246', 'SANTA ELENA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (137, '5182', 'SAUCE ARRIBA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (138, '5857', 'SEGUNDA USINA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (139, '5281', 'SIMBOLAR', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (140, '5837', 'SUCO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (141, '5297', 'TALA CANADA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (142, '5153', 'TALA HUASI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (143, '5291', 'TALAINI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (144, '5131', 'TINOCO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (145, '5139', 'TORO PUJIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (146, '5289', 'TOSNO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (147, '5284', 'TUCLAME', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (148, '5189', 'VALLE DE ANISACATE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (149, '5199', 'VILLA AMANCAY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (150, '5249', 'VILLA CANDELARIA NORTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (151, '5107', 'VILLA CERRO AZUL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (152, '5189', 'VILLA CIUDAD PARQUE LOS REARTES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (153, '5887', 'VILLA CIUDAD DE AMERICA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (154, '5801', 'VILLA EL CHACAY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (155, '2594', 'VILLA ELISA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (156, '5212', 'VILLA GUTIERREZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (157, '5189', 'VILLA LA BOLSA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (158, '5186', 'VILLA LOS AROMOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (159, '2551', 'VILLA LOS PATOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (160, '5152', 'VILLA PARQUE SIQUIMAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (161, '5859', 'VILLA QUILLINZO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (162, '5947', 'VILLA SAN ESTEBAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (163, '5189', 'VILLA SAN ISIDRO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (164, '5871', 'VILLA SARMIENTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (165, '5299', 'VILLA DE POCHO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (166, '5186', 'VILLA DEL PRADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (167, '6144', 'WASHINGTON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (168, '5833', 'ACHIRAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (169, '5843', 'ADELIA MARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (170, '5107', 'AGUA DE ORO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (171, '5813', 'ALCIRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (172, '2686', 'ALEJANDRO ROCA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (173, '2662', 'ALEJO LEDESMA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (174, '5949', 'ALICIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (175, '5854', 'ALMAFUERTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (176, '5801', 'ALPA CORRAL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (177, '5186', 'ALTA GRACIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (178, '5907', 'ALTO ALEGRE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (179, '2417', 'ALTOS DE CHIPION', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (180, '5189', 'ANISACATE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (181, '2624', 'ARIAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (182, '2434', 'ARROYITO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (183, '5909', 'ARROYO ALGODON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (184, '5917', 'ARROYO CABRAL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (185, '5901', 'AUSONIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (186, '2572', 'BALLESTEROS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (187, '2572', 'BALLESTEROS SUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (188, '5141', 'BALNEARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (189, '2550', 'BELL VILLE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (190, '5807', 'BENGOLEA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (191, '2664', 'BENJAMIN GOULD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (192, '5817', 'BERROTARAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (193, '5158', 'BIALET MASSE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (194, '5119', 'BOUWER', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (195, '2419', 'BRINKMANN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (196, '6225', 'BUCHARDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (197, '5845', 'BULNES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (198, '5969', 'CALCHIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (199, '5965', 'CALCHIN OESTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (200, '2585', 'CAMILO ALDAO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (201, '2650', 'CANALS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (202, '5963', 'CAPILLA DEL CARMEN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (203, '5184', 'CAPILLA DEL MONTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (204, '2645', 'CAPITAN GENERAL BERNARDO OHIGGINS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (205, '5805', 'CARNERILLO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (206, '5915', 'CARRILOBO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (207, '2625', 'CAVANAGH', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (208, '5229', 'CANADA DE LUQUE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (209, '5837', 'CHAJAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (210, '5807', 'CHARRAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (211, '2675', 'CHAZON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (212, '2561', 'CHILIBROSTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (213, '2559', 'CINTRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (214, '5965', 'COLAZO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (215, '5987', 'COLONIA ALMADA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (216, '2651', 'COLONIA BISMARCK', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (217, '5223', 'COLONIA CAROYA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (218, '2645', 'COLONIA ITALIANA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (219, '2424', 'COLONIA MARINA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (220, '2423', 'COLONIA PROSPERIDAD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (221, '2426', 'COLONIA SAN BARTOLOME', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (222, '5101', 'COLONIA TIROLESA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (223, '2419', 'COLONIA VIGNAUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (224, '5811', 'CORONEL BAIGORRIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (225, '5847', 'CORONEL MOLDES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (226, '2645', 'CORRAL DE BUSTOS IFFLINGER', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (227, '5853', 'CORRALITO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (228, '5166', 'COSQUIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (229, '5961', 'COSTA SACATE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (230, '2189', 'CRUZ ALTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (231, '5280', 'CRUZ DEL EJE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (232, '5000', 'CORDOBA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (233, '5919', 'DALMACIO VELEZ SARSFIELD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (234, '6271', 'DEL CAMPILLO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (235, '5121', 'DESPENADEROS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (236, '2424', 'DEVOTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (237, '5200', 'DEAN FUNES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (238, '5947', 'EL ARANADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (239, '5281', 'EL BRETE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (240, '5951', 'EL FORTIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (241, '2432', 'EL TIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (242, '5815', 'ELENA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (243, '5856', 'EMBALSE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (244, '5145', 'ESTACION GENERAL PAZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (245, '5045', 'ESTACION JUAREZ CELMAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (246, '2681', 'ETRURIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (247, '2413', 'FREYRE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (248, '2583', 'GENERAL BALDISSERA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (249, '5809', 'GENERAL CABRERA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (250, '5923', 'GENERAL DEHEZA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (251, '6132', 'GENERAL LEVALLE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (252, '2592', 'GENERAL ROCA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (253, '2627', 'GUATIMOZIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (254, '5929', 'HERNANDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (255, '6121', 'HUANCHILLA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (256, '5174', 'HUERTA GRANDE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (257, '6270', 'HUINCA RENANCO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (258, '2557', 'IDIAZABAL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (259, '2587', 'INRIVILLE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (260, '2661', 'ISLA VERDE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (261, '6271', 'ITALO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (262, '5984', 'JAMES CRAIK', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (263, '5220', 'JESUS MARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (264, '6127', 'JOVITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (265, '2553', 'JUSTINIANO POSSE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (266, '5151', 'LA CALERA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (267, '2670', 'LA CARLOTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (268, '6142', 'LA CAUTIVA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (269, '6101', 'LA CESIRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (270, '5859', 'LA CRUZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (271, '5178', 'LA CUMBRE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (272, '5172', 'LA FALDA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (273, '2426', 'LA FRANCIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (274, '5115', 'LA GRANJA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (275, '5284', 'LA LAGUNA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (276, '5925', 'LA PALESTINA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (277, '2417', 'LA PAQUITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (278, '5137', 'LA PARA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (279, '5879', 'LA PAZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (280, '5911', 'LA PLAYOSA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (281, '5101', 'LA PUERTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (282, '2435', 'LA TORDILLA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (283, '2657', 'LABORDE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (284, '6120', 'LABOULAYE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (285, '5974', 'LAGUNA LARGA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (286, '5848', 'LAS ACEQUIAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (287, '5231', 'LAS ARRIAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (288, '5805', 'LAS HIGUERAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (289, '5965', 'LAS JUNTURAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (290, '5921', 'LAS PERDICES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (291, '5238', 'LAS PENAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (292, '5885', 'LAS TAPIAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (293, '5941', 'LAS VARAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (294, '5940', 'LAS VARILLAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (295, '5839', 'LAS VERTIENTES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (296, '2594', 'LEONES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (297, '5871', 'LOS CERRILLOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (298, '2684', 'LOS CISNES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (299, '5182', 'LOS COCOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (300, '5823', 'LOS CONDORES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (301, '2581', 'LOS SURGENTES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (302, '5901', 'LOS ZORROS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (303, '5101', 'LOZADA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (304, '5917', 'LUCA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (305, '5216', 'LUCIO VICTORIO MANSILLA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (306, '5967', 'LUQUE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (307, '5101', 'MALAGUENO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (308, '5125', 'MALVINAS ARGENTINAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (309, '5988', 'MANFREDI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (310, '2580', 'MARCOS JUAREZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (311, '5139', 'MARULL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (312, '5965', 'MATORRALES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (313, '6271', 'MATTALDI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (314, '6123', 'MELO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (315, '5107', 'MENDIOLAZA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (316, '5125', 'MI GRANJA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (317, '5889', 'MINA CLAVERO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (318, '5143', 'MIRAMAR DE ANSENUZA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (319, '2589', 'MONTE BUEY', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (320, '2564', 'MONTE LENA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (321, '2659', 'MONTE MAIZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (322, '5119', 'MONTE RALO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (323, '5831', 'MONTE DE LOS GAUCHOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (324, '5125', 'MONTECRISTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (325, '2568', 'MORRISON', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (326, '2421', 'MORTEROS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (327, '2563', 'NOETINGER', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (328, '5887', 'NONO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (329, '5225', 'OBISPO TREJO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (330, '5807', 'OLAETA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (331, '5980', 'OLIVA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (332, '5986', 'ONCATIVO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (333, '2555', 'ORDONEZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (334, '5931', 'PAMPAYASTA SUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (335, '2679', 'PASCANAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (336, '5925', 'PASCO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (337, '5972', 'PILAR', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (338, '5125', 'PIQUILLIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (339, '2415', 'PORTENA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (340, '5913', 'POZO DEL MOLLE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (341, '2651', 'PUEBLO ITALIANO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (342, '2423', 'QUEBRACHO HERRADO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (343, '5214', 'QUILINO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (344, '5803', 'REDUCCION', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (345, '6128', 'ROSALES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (346, '5111', 'RIO CEBALLOS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (347, '5800', 'RIO CUARTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (348, '5127', 'RIO PRIMERO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (349, '5960', 'RIO SEGUNDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (350, '5850', 'RIO TERCERO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (351, '5821', 'RIO DE LOS SAUCES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (352, '5945', 'SACANTA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (353, '2525', 'SAIRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (354, '5149', 'SALDAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (355, '5295', 'SALSACATE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (356, '5113', 'SALSIPUEDES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (357, '5829', 'SAMPACHO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (358, '5191', 'SAN AGUSTIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (359, '5153', 'SAN ANTONIO DE ARREDONDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (360, '2559', 'SAN ANTONIO DE LITIN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (361, '5841', 'SAN BASILIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (362, '5291', 'SAN CARLOS MINAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (363, '5182', 'SAN ESTEBAN', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (364, '2400', 'SAN FRANCISCO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (365, '5209', 'SAN FRANCISCO DEL CHANAR', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (366, '5875', 'SAN JAVIER Y YACANTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (367, '5871', 'SAN JOSE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (368, '5244', 'SAN JOSE DE LA DORMIDA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (369, '5216', 'SAN JOSE DE LAS SALINAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (370, '5282', 'SAN MARCOS SIERRA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (371, '2566', 'SAN MARCOS SUD', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (372, '5871', 'SAN PEDRO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (373, '5205', 'SAN PEDRO NORTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (374, '5825', 'SANTA CATALINA HOLMBERG', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (375, '2671', 'SANTA EUFEMIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (376, '5164', 'SANTA MARIA DE PUNILLA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (377, '5196', 'SANTA ROSA DE CALAMUCHITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (378, '5125', 'SANTIAGO TEMPLE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (379, '5212', 'SARMIENTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (380, '5943', 'SATURNINO MARIA LASPIUR', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (381, '5231', 'SEBASTIAN ELCANO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (382, '2419', 'SEEBER', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (383, '6125', 'SERRANO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (384, '5270', 'SERREZUELA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (385, '5907', 'SILVIO PELLICO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (386, '5220', 'SINSACATE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (387, '5933', 'TANCACHA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (388, '5155', 'TANTI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (389, '5927', 'TICINO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (390, '5123', 'TOLEDO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (391, '6141', 'TOSQUITA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (392, '2436', 'TRANSITO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (393, '5936', 'TIO PUJIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (394, '2677', 'UCACHA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (395, '5109', 'UNQUILLO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (396, '5168', 'VALLE HERMOSO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (397, '2671', 'VIAMONTE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (398, '6140', 'VICUNA MACKENNA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (399, '5105', 'VILLA ALLENDE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (400, '5935', 'VILLA ASCASUBI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (401, '5152', 'VILLA CARLOS PAZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (402, '2433', 'VILLA CONCEPCION DEL TIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (403, '5891', 'VILLA CURA BROCHERO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (404, '5870', 'VILLA DOLORES', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (405, '5137', 'VILLA FONTANA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (406, '5194', 'VILLA GENERAL BELGRANO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (407, '5176', 'VILLA GIARDINO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (408, '6275', 'VILLA HUIDOBRO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (409, '5220', 'VILLA MARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (410, '5903', 'VILLA NUEVA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (411, '5101', 'VILLA PARQUE SANTA ANA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (412, '6128', 'VILLA ROSSI', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (413, '5864', 'VILLA RUMIPAL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (414, '5153', 'VILLA RIO ICHO CRUZ', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (415, '5152', 'VILLA SANTA CRUZ DEL LAGO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (416, '5133', 'VILLA SANTA ROSA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (417, '5871', 'VILLA SARMIENTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (418, '5203', 'VILLA TULUMBA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (419, '6273', 'VILLA VALERIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (420, '5197', 'VILLA YACANTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (421, '5248', 'VILLA DE MARIA', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (422, '5284', 'VILLA DE SOTO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (423, '5885', 'VILLA DE LAS ROSAS', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (424, '5862', 'VILLA DEL DIQUE', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (425, '5963', 'VILLA DEL ROSARIO', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (426, '5236', 'VILLA DEL TOTORAL', 5);
INSERT INTO public."city" (id,"zip_code","name",province_id) VALUES (427, '2655', 'WENCESLAO ESCALANTE', 5);
