--liquibase formatted sql

--changeset AgustinAnil:crear_tabla_assets
CREATE TABLE media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner BIGINT,
    bucket VARCHAR(50) NOT NULL,
    object_key TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (bucket, object_key),
    CONSTRAINT fk_media_asset_user
    FOREIGN KEY (owner) REFERENCES "users"(id) ON DELETE CASCADE
);

COMMENT ON COLUMN public.media_asset."owner" IS 'A quien corresponde la imagen, puede ser a un usuario o a la app';
COMMENT ON COLUMN public.media_asset.bucket IS 'Bucket de Cloudflare';
COMMENT ON COLUMN public.media_asset.object_key IS 'Identificador de la imagen en el bucket';
COMMENT ON COLUMN public.media_asset.filename IS 'Nombre del archivo';
COMMENT ON COLUMN public.media_asset.content_type IS 'Tipo de contenido de la imagen';
COMMENT ON COLUMN public.media_asset.bytes_size IS 'Tamanio';
COMMENT ON COLUMN public.media_asset.created_at IS 'Fecha de cracion';