--liquibase formatted sql

--changeset SantiGodoy:crear_tipos_de_vehiculos_por_defecto_01
INSERT INTO public."vehicle_type" (id, "name", "description") VALUES 
(1, 'SEDAN', 'VEHICULO IDEAL PARA VIAJES, CON BAUL SEPARADO'),
(2, 'COMPACTO', 'VEHICULO PEQUEÑO DE DOS PUERTAS, CON BAUL SEPARADO'),
(3, 'FAMILIAR', 'VEHICULO DE CUATRO PUERTAS CON GRAN ESPACIO PARA PASAJEROS Y BAUL AMPLIO'),
(4, 'SUV', 'VEHICULO DE MAYOR ALTURA, APROVECHANDO ESPACIO Y VERSATILIDAD, CON BAUL SEPARADO'),
(5, 'CAMIONETA', 'VEHICULO DE CARGA LIGERA CON ESPACIO TRASERO ABIERTO'),
(6, 'PICK-UP', 'VEHICULO ROBUSTO CON CAJA DE CARGA EXTERNA'),
(7, 'MOTOCICLETA', 'VEHICULO DE DOS RUEDAS, SIN BAUL NI PUERTAS'),
(8, 'DEPORTIVO', 'VEHICULO DE ALTA PERFORMANCE, BAJO Y CON ESTILO AGRESIVO'),
(9, 'FURGONETA', 'VEHICULO DE GRAN CAPACIDAD PARA PASAJEROS O CARGA')
ON CONFLICT (id) DO NOTHING;

