package com.carpool.carpool.dto.google;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Schema(description = "Dato necesario para validar token ID Google")
public class GoogleAuthRequestDTO {

    @NotBlank(message = "El token de Google no puede quedar en blanco.")
    @Schema(example = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhlOGZjOGU1NTZmN2E3NmQwOGQzNTgyOWQ2ZjkwYWUyZTEyY2ZkMGQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4NzYzODgyODQ1NDItdHY3b2FoaTBnZjEwZjFvMmpyMHA3bDdvYWlhaDlkbTAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4NzYzODgyODQ1NDItdHY3b2FoaTBnZjEwZjFvMmpyMHA3bDdvYWlhaDlkbTAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDQ5OTYxMjIyNjgzMDE1ODc1NTQiLCJlbWFpbCI6ImFyZ2NhcnBvb2xAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJtbGxuY1lkQzNYSVZPWHNQd2JyVzlRIiwibmFtZSI6IkNhcnBvb2wiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS29EamN4T1hZcENjQ0p1dlVBbjMzbDFKNUotUjZwR2tjeXdVSjF3dGs1b3c5YkJRPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkNhcnBvb2wiLCJpYXQiOjE3NTIyNjg2MTQsImVYiVnY7_i1yEsKePDvYRaSgfrthrtcqiXZMT4qXbnrydGAEk42VQjKUirt345asdqYG2ZY-W2UXOVcnyXqNxGorl_acjDGPNs5vLiaWfasdar1rthrhtGtqGUzYn2szc6_m06XYxXPnYuK8c0MVLff9Uicn09TjadznGOAoc0KM-l8I1RPqH2JunRRlBz-GjgcWMyCw6_3rpdCpgwV1x_f-nJIOukEdTfjRQ73bGMr2kk7ifLxgtyHxgra-TQ_brCZrBB2dakH5ZOivIuTzM34M-K5B1Wp5yT49u_9_Yu7SYKfxqSVcXNMjAL9Ow")
    private String idToken;
}
