#Configuration
spring.application.name=carpool
server.servlet.context-path=/carpool/api/v1
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#Database
spring.datasource.url=jdbc:postgresql://localhost:5433/carpool-db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql= true

#Liquibase
spring.liquibase.change-log=classpath:changelog/db.changelog-master.xml
spring.liquibase.enabled=false
spring.liquibase.drop-first=false

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Google
google.client-id=876388284542-tv7oahi0gf10f1o2jr0p7l7oaiah9dm0.apps.googleusercontent.com
redirect.validate.email=http://localhost:3000/email-verified?token=value

#Password Change
redirect.password.change=http://localhost:3000/password-change?token=value

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=argcarpool@gmail.com
spring.mail.password=ftff xylj xcqh kzfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Recaptcha
recaptcha.verifyUrl=https://www.google.com/recaptcha/api/siteverify
recaptcha.secretKey=6Le70YArAAAAAFOY7T6gxIL7fzu2PpSWS1H7uO8j

#Cloudflare R2
cloudflare.r2.endpoint=https://5dce6dd8fd2b8c12742c81bbb251a9ca.r2.cloudflarestorage.com/
cloudflare.r2.public.endpoint=https://pub-15165322192045ea9751c967a7ea3853.r2.dev/
cloudflare.r2.bucket-private=carpool-media
cloudflare.r2.bucket-public=carpool-app
cloudflare.r2.access-key=83fbceb50562cfb302f0ea50fb82967b
cloudflare.r2.secret-key=0eb6c66e44c0379a468cb152cae1dd07881c3bee42c9e2a6ae9752e251221bc9

logging.level.org.springframework.security=trace
