name: Notificar cambios en desarrollo

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notificar Discord
        run: |
          MESSAGE="-----------------------------------------------
          
          Nuevos cambios en rama dev
          Fecha: ${{ github.event.head_commit.timestamp }}
          Autor: ${{ github.actor }}
          Commit: ${{ github.event.head_commit.message }}
          
          -----------------------------------------------"

          MESSAGE_JSON=$(echo "$MESSAGE" | sed ':a;N;$!ba;s/\n/\\n/g')
          
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"$MESSAGE_JSON\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
